// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/common/base64/file": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/cron/start": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/cron/stat": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/cron/stop": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/download/file": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/download/file/{seqno}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "seqno",
                        "name": "seqno",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/local/file": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/signPdf": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/signPdfAsync": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/upload/file": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/verifyRoamingCert": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/verifyRoamingCertAsync": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/verifyRoamingPin": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/verifyRoamingPinAsync": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/dss/signPdf": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DSS"
                ],
                "parameters": [
                    {
                        "description": "SignPdfConfigB DTO",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostSignPdfConfigB"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/dss/verifyRoamingCert": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DSS"
                ],
                "parameters": [
                    {
                        "description": "VerifyRoamingCert DTO",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostVerifyRoamingCert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/dss/verifyRoamingPin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DSS"
                ],
                "parameters": [
                    {
                        "description": "VerifyRoamingPin DTO",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostVerifyRoamingPin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/test/base64/file": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/test/download/file": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/test/local/file": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/test/signPdf": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/test/upload/file": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.PostSignPdfConfigB": {
            "type": "object",
            "required": [
                "dest",
                "dtsFlag",
                "fileServerId",
                "orgId",
                "pCode",
                "pin",
                "signerXyPage",
                "source",
                "userId"
            ],
            "properties": {
                "customSignatureText": {
                    "type": "string",
                    "maxLength": 80
                },
                "dest": {
                    "type": "string",
                    "maxLength": 300,
                    "minLength": 1
                },
                "dtsFlag": {
                    "type": "integer",
                    "default": 1,
                    "maximum": 1,
                    "minimum": 1
                },
                "fileServerId": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1
                },
                "orgId": {
                    "type": "string",
                    "maxLength": 45,
                    "minLength": 1
                },
                "pCode": {
                    "type": "string",
                    "maxLength": 45,
                    "minLength": 1
                },
                "pin": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 1
                },
                "qrPosition": {
                    "type": "string",
                    "maxLength": 300
                },
                "qrSize": {
                    "type": "integer",
                    "default": 0,
                    "maximum": 3
                },
                "qrValue": {
                    "type": "string",
                    "maxLength": 200
                },
                "remark": {
                    "type": "string",
                    "maxLength": 300
                },
                "signerFontSize": {
                    "type": "integer",
                    "maximum": 3
                },
                "signerImagePath": {
                    "type": "string",
                    "maxLength": 300
                },
                "signerTextRow": {
                    "type": "integer",
                    "maximum": 3
                },
                "signerXyPage": {
                    "type": "string",
                    "maxLength": 300,
                    "minLength": 1
                },
                "source": {
                    "type": "string",
                    "maxLength": 300,
                    "minLength": 1
                },
                "userId": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1
                }
            }
        },
        "dto.PostVerifyRoamingCert": {
            "type": "object",
            "required": [
                "orgId",
                "pCode",
                "userId"
            ],
            "properties": {
                "orgId": {
                    "type": "string",
                    "maxLength": 45,
                    "minLength": 1
                },
                "pCode": {
                    "type": "string",
                    "maxLength": 45,
                    "minLength": 1
                },
                "userId": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1
                }
            }
        },
        "dto.PostVerifyRoamingPin": {
            "type": "object",
            "required": [
                "orgId",
                "pCode",
                "pin",
                "userId"
            ],
            "properties": {
                "orgId": {
                    "type": "string",
                    "maxLength": 45,
                    "minLength": 1
                },
                "pCode": {
                    "type": "string",
                    "maxLength": 45,
                    "minLength": 1
                },
                "pin": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 1
                },
                "userId": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/signpdf",
	Schemes:          []string{},
	Title:            "Swagger Sign PDF API",
	Description:      "This is a sign pdf server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
