SELECT * FROM ESIGN_EVENTS ee 
WHERE ee.EVENT_SEQ_NO ='429'

SELECT * FROM ESIGN_SIGN_PDF_RESP espr 
WHERE espr.EVENT_SEQ_NO ='429'

UPDATE ESIGN_EVENTS SET PROCESS_FLG ='U', SIGN_PDF_START_TIME =NULL, SIGN_PDF_END_TIME =NULL
WHERE EVENT_SEQ_NO IN ('429')

SELECT * from ESIGN_EVENTS WHERE EVENT_SEQ_NO 
IN (SELECT EVENT_SEQ_NO FROM ESIGN_SIGN_PDF_RESP espr WHERE espr.STATUS_CODE <> '901')