SELECT * FROM ESIGN_EVENTS ee 
WHERE ee.PROCESS_FLG <> 'Y'
ORDER BY ee.CREATION_DATE_TIME 

SELECT * FROM ESIGN_EVENTS ee 
WHERE ee.PROCESS_FLG = 'Y'
ORDER BY ee.CREATION_DATE_TIME desc 

SELECT * FROM ESIGN_EVENTS ee 
WHERE ee.EVENT_SEQ_NO ='6145'

SELECT * FROM ESIGN_SIGN_PDF_RESP espr 
WHERE espr.STATUS_CODE <>'901'

SELECT * FROM ESIGN_SIGN_PDF_REQ espr 
WHERE espr.EVENT_SEQ_NO ='5154'

SELECT
E.EVENT_SEQ_NO, E.CREATION_DATE_TIME, E.PRN, E.PATIENT_NAME,
E.ACCOUNT_NUMBER, E.SCRIPT_NO, E.DOCTOR_MCR, E.DOCTOR_NAME, REQ.USER_ID AS PRESCRIBER_ID_NO, REQ.PIN AS PRESCRIBER_CERT_PIN,
RESP.STATUS_CODE, RESP.STATUS_MESSAGE, RESP.LAST_API_CALL
FROM ESIGN_EVENTS E, ESIGN_SIGN_PDF_REQ REQ, ESIGN_SIGN_PDF_RESP RESP
WHERE E.EVENT_SEQ_NO = RESP.EVENT_SEQ_NO
AND RESP.EVENT_SEQ_NO = REQ.EVENT_SEQ_NO
AND RESP.STATUS_CODE <> '901'
ORDER BY TO_NUMBER(E.EVENT_SEQ_NO) ASC